<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Enums\Status;
use App\Models\Country;
use App\Models\State;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $countries = [
            ['name' => 'Afganistan', 'code' => 'AF', 'phone' => 93],
            ['name' => 'Arnavutluk', 'code' => 'AL', 'phone' => 355],
            ['name' => 'Cezayir', 'code' => 'DZ', 'phone' => 213],
            ['name' => 'Andorra', 'code' => 'AD', 'phone' => 376],
            ['name' => 'Angola', 'code' => 'AO', 'phone' => 244],
            ['name' => 'Antigua ve Barbuda', 'code' => 'AG', 'phone' => 1268],
            ['name' => 'Arjantin', 'code' => 'AR', 'phone' => 54],
            ['name' => 'Ermenistan', 'code' => 'AM', 'phone' => 374],
            ['name' => 'Avustralya', 'code' => 'AU', 'phone' => 61],
            ['name' => 'Avusturya', 'code' => 'AT', 'phone' => 43],
            ['name' => 'Azerbaycan', 'code' => 'AZ', 'phone' => 994],
            ['name' => 'Bahamalar', 'code' => 'BS', 'phone' => 1242],
            ['name' => 'Bahreyn', 'code' => 'BH', 'phone' => 973],
            ['name' => 'Bangladeş', 'code' => 'BD', 'phone' => 880],
            ['name' => 'Barbados', 'code' => 'BB', 'phone' => 1246],
            ['name' => 'Belarus', 'code' => 'BY', 'phone' => 375],
            ['name' => 'Belçika', 'code' => 'BE', 'phone' => 32],
            ['name' => 'Belize', 'code' => 'BZ', 'phone' => 501],
            ['name' => 'Benin', 'code' => 'BJ', 'phone' => 229],
            ['name' => 'Butan', 'code' => 'BT', 'phone' => 975],
            ['name' => 'Bolivya', 'code' => 'BO', 'phone' => 591],
            ['name' => 'Bosna Hersek', 'code' => 'BA', 'phone' => 387],
            ['name' => 'Botsvana', 'code' => 'BW', 'phone' => 267],
            ['name' => 'Brezilya', 'code' => 'BR', 'phone' => 55],
            ['name' => 'Brunei', 'code' => 'BN', 'phone' => 673],
            ['name' => 'Bulgaristan', 'code' => 'BG', 'phone' => 359],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'phone' => 226],
            ['name' => 'Burundi', 'code' => 'BI', 'phone' => 257],
            ['name' => 'Kamboçya', 'code' => 'KH', 'phone' => 855],
            ['name' => 'Kamerun', 'code' => 'CM', 'phone' => 237],
            ['name' => 'Kanada', 'code' => 'CA', 'phone' => 1],
            ['name' => 'Yeşil Burun Adaları', 'code' => 'CV', 'phone' => 238],
            ['name' => 'Orta Afrika Cumhuriyeti', 'code' => 'CF', 'phone' => 236],
            ['name' => 'Çad', 'code' => 'TD', 'phone' => 235],
            ['name' => 'Şili', 'code' => 'CL', 'phone' => 56],
            ['name' => 'Çin', 'code' => 'CN', 'phone' => 86],
            ['name' => 'Kolombiya', 'code' => 'CO', 'phone' => 57],
            ['name' => 'Komorlar', 'code' => 'KM', 'phone' => 269],
            ['name' => 'Kongo', 'code' => 'CG', 'phone' => 242],
            ['name' => 'Kosta Rika', 'code' => 'CR', 'phone' => 506],
            ['name' => 'Hırvatistan', 'code' => 'HR', 'phone' => 385],
            ['name' => 'Küba', 'code' => 'CU', 'phone' => 53],
            ['name' => 'Kıbrıs', 'code' => 'CY', 'phone' => 357],
            ['name' => 'Çek Cumhuriyeti', 'code' => 'CZ', 'phone' => 420],
            ['name' => 'Danimarka', 'code' => 'DK', 'phone' => 45],
            ['name' => 'Cibuti', 'code' => 'DJ', 'phone' => 253],
            ['name' => 'Dominika', 'code' => 'DM', 'phone' => 1767],
            ['name' => 'Dominik Cumhuriyeti', 'code' => 'DO', 'phone' => 1809],
            ['name' => 'Ekvador', 'code' => 'EC', 'phone' => 593],
            ['name' => 'Mısır', 'code' => 'EG', 'phone' => 20],
            ['name' => 'El Salvador', 'code' => 'SV', 'phone' => 503],
            ['name' => 'Ekvator Ginesi', 'code' => 'GQ', 'phone' => 240],
            ['name' => 'Eritre', 'code' => 'ER', 'phone' => 291],
            ['name' => 'Estonya', 'code' => 'EE', 'phone' => 372],
            ['name' => 'Etiyopya', 'code' => 'ET', 'phone' => 251],
            ['name' => 'Fiji', 'code' => 'FJ', 'phone' => 679],
            ['name' => 'Finlandiya', 'code' => 'FI', 'phone' => 358],
            ['name' => 'Fransa', 'code' => 'FR', 'phone' => 33],
            ['name' => 'Gabon', 'code' => 'GA', 'phone' => 241],
            ['name' => 'Gambiya', 'code' => 'GM', 'phone' => 220],
            ['name' => 'Gürcistan', 'code' => 'GE', 'phone' => 995],
            ['name' => 'Almanya', 'code' => 'DE', 'phone' => 49],
            ['name' => 'Gana', 'code' => 'GH', 'phone' => 233],
            ['name' => 'Yunanistan', 'code' => 'GR', 'phone' => 30],
            ['name' => 'Grenada', 'code' => 'GD', 'phone' => 1473],
            ['name' => 'Guatemala', 'code' => 'GT', 'phone' => 502],
            ['name' => 'Gine', 'code' => 'GN', 'phone' => 224],
            ['name' => 'Gine-Bissau', 'code' => 'GW', 'phone' => 245],
            ['name' => 'Guyana', 'code' => 'GY', 'phone' => 592],
            ['name' => 'Haiti', 'code' => 'HT', 'phone' => 509],
            ['name' => 'Honduras', 'code' => 'HN', 'phone' => 504],
            ['name' => 'Macaristan', 'code' => 'HU', 'phone' => 36],
            ['name' => 'İzlanda', 'code' => 'IS', 'phone' => 354],
            ['name' => 'Hindistan', 'code' => 'IN', 'phone' => 91],
            ['name' => 'Endonezya', 'code' => 'ID', 'phone' => 62],
            ['name' => 'İran', 'code' => 'IR', 'phone' => 98],
            ['name' => 'Irak', 'code' => 'IQ', 'phone' => 964],
            ['name' => 'İrlanda', 'code' => 'IE', 'phone' => 353],
            ['name' => 'İsrail', 'code' => 'IL', 'phone' => 972],
            ['name' => 'İtalya', 'code' => 'IT', 'phone' => 39],
            ['name' => 'Jamaika', 'code' => 'JM', 'phone' => 1876],
            ['name' => 'Japonya', 'code' => 'JP', 'phone' => 81],
            ['name' => 'Ürdün', 'code' => 'JO', 'phone' => 962],
            ['name' => 'Kazakistan', 'code' => 'KZ', 'phone' => 7],
            ['name' => 'Kenya', 'code' => 'KE', 'phone' => 254],
            ['name' => 'Kiribati', 'code' => 'KI', 'phone' => 686],
            ['name' => 'Kuzey Kore', 'code' => 'KP', 'phone' => 850],
            ['name' => 'Güney Kore', 'code' => 'KR', 'phone' => 82],
            ['name' => 'Kuveyt', 'code' => 'KW', 'phone' => 965],
            ['name' => 'Kırgızistan', 'code' => 'KG', 'phone' => 996],
            ['name' => 'Laos', 'code' => 'LA', 'phone' => 856],
            ['name' => 'Letonya', 'code' => 'LV', 'phone' => 371],
            ['name' => 'Lübnan', 'code' => 'LB', 'phone' => 961],
            ['name' => 'Lesotho', 'code' => 'LS', 'phone' => 266],
            ['name' => 'Liberya', 'code' => 'LR', 'phone' => 231],
            ['name' => 'Libya', 'code' => 'LY', 'phone' => 218],
            ['name' => 'Lihtenştayn', 'code' => 'LI', 'phone' => 423],
            ['name' => 'Litvanya', 'code' => 'LT', 'phone' => 370],
            ['name' => 'Lüksemburg', 'code' => 'LU', 'phone' => 352],
            ['name' => 'Madagaskar', 'code' => 'MG', 'phone' => 261],
            ['name' => 'Malavi', 'code' => 'MW', 'phone' => 265],
            ['name' => 'Malezya', 'code' => 'MY', 'phone' => 60],
            ['name' => 'Maldivler', 'code' => 'MV', 'phone' => 960],
            ['name' => 'Mali', 'code' => 'ML', 'phone' => 223],
            ['name' => 'Malta', 'code' => 'MT', 'phone' => 356],
            ['name' => 'Moritanya', 'code' => 'MR', 'phone' => 222],
            ['name' => 'Mauritius', 'code' => 'MU', 'phone' => 230],
            ['name' => 'Meksika', 'code' => 'MX', 'phone' => 52],
            ['name' => 'Moldova', 'code' => 'MD', 'phone' => 373],
            ['name' => 'Monako', 'code' => 'MC', 'phone' => 377],
            ['name' => 'Moğolistan', 'code' => 'MN', 'phone' => 976],
            ['name' => 'Karadağ', 'code' => 'ME', 'phone' => 382],
            ['name' => 'Fas', 'code' => 'MA', 'phone' => 212],
            ['name' => 'Mozambik', 'code' => 'MZ', 'phone' => 258],
            ['name' => 'Myanmar', 'code' => 'MM', 'phone' => 95],
            ['name' => 'Namibya', 'code' => 'NA', 'phone' => 264],
            ['name' => 'Nauru', 'code' => 'NR', 'phone' => 674],
            ['name' => 'Nepal', 'code' => 'NP', 'phone' => 977],
            ['name' => 'Hollanda', 'code' => 'NL', 'phone' => 31],
            ['name' => 'Yeni Zelanda', 'code' => 'NZ', 'phone' => 64],
            ['name' => 'Nikaragua', 'code' => 'NI', 'phone' => 505],
            ['name' => 'Nijer', 'code' => 'NE', 'phone' => 227],
            ['name' => 'Nijerya', 'code' => 'NG', 'phone' => 234],
            ['name' => 'Norveç', 'code' => 'NO', 'phone' => 47],
            ['name' => 'Umman', 'code' => 'OM', 'phone' => 968],
            ['name' => 'Pakistan', 'code' => 'PK', 'phone' => 92],
            ['name' => 'Palau', 'code' => 'PW', 'phone' => 680],
            ['name' => 'Panama', 'code' => 'PA', 'phone' => 507],
            ['name' => 'Papua Yeni Gine', 'code' => 'PG', 'phone' => 675],
            ['name' => 'Paraguay', 'code' => 'PY', 'phone' => 595],
            ['name' => 'Peru', 'code' => 'PE', 'phone' => 51],
            ['name' => 'Filipinler', 'code' => 'PH', 'phone' => 63],
            ['name' => 'Polonya', 'code' => 'PL', 'phone' => 48],
            ['name' => 'Portekiz', 'code' => 'PT', 'phone' => 351],
            ['name' => 'Katar', 'code' => 'QA', 'phone' => 974],
            ['name' => 'Romanya', 'code' => 'RO', 'phone' => 40],
            ['name' => 'Rusya', 'code' => 'RU', 'phone' => 7],
            ['name' => 'Ruanda', 'code' => 'RW', 'phone' => 250],
            ['name' => 'Saint Kitts ve Nevis', 'code' => 'KN', 'phone' => 1869],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'phone' => 1758],
            ['name' => 'Saint Vincent ve Grenadinler', 'code' => 'VC', 'phone' => 1784],
            ['name' => 'Samoa', 'code' => 'WS', 'phone' => 685],
            ['name' => 'San Marino', 'code' => 'SM', 'phone' => 378],
            ['name' => 'Sao Tome ve Principe', 'code' => 'ST', 'phone' => 239],
            ['name' => 'Suudi Arabistan', 'code' => 'SA', 'phone' => 966],
            ['name' => 'Senegal', 'code' => 'SN', 'phone' => 221],
            ['name' => 'Sırbistan', 'code' => 'RS', 'phone' => 381],
            ['name' => 'Seyşeller', 'code' => 'SC', 'phone' => 248],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'phone' => 232],
            ['name' => 'Singapur', 'code' => 'SG', 'phone' => 65],
            ['name' => 'Slovakya', 'code' => 'SK', 'phone' => 421],
            ['name' => 'Slovenya', 'code' => 'SI', 'phone' => 386],
            ['name' => 'Solomon Adaları', 'code' => 'SB', 'phone' => 677],
            ['name' => 'Somali', 'code' => 'SO', 'phone' => 252],
            ['name' => 'Güney Afrika', 'code' => 'ZA', 'phone' => 27],
            ['name' => 'Güney Sudan', 'code' => 'SS', 'phone' => 211],
            ['name' => 'İspanya', 'code' => 'ES', 'phone' => 34],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'phone' => 94],
            ['name' => 'Sudan', 'code' => 'SD', 'phone' => 249],
            ['name' => 'Surinam', 'code' => 'SR', 'phone' => 597],
            ['name' => 'Svaziland', 'code' => 'SZ', 'phone' => 268],
            ['name' => 'İsveç', 'code' => 'SE', 'phone' => 46],
            ['name' => 'İsviçre', 'code' => 'CH', 'phone' => 41],
            ['name' => 'Suriye', 'code' => 'SY', 'phone' => 963],
            ['name' => 'Tayvan', 'code' => 'TW', 'phone' => 886],
            ['name' => 'Tacikistan', 'code' => 'TJ', 'phone' => 992],
            ['name' => 'Tanzanya', 'code' => 'TZ', 'phone' => 255],
            ['name' => 'Tayland', 'code' => 'TH', 'phone' => 66],
            ['name' => 'Togo', 'code' => 'TG', 'phone' => 228],
            ['name' => 'Tonga', 'code' => 'TO', 'phone' => 676],
            ['name' => 'Trinidad ve Tobago', 'code' => 'TT', 'phone' => 1868],
            ['name' => 'Tunus', 'code' => 'TN', 'phone' => 216],
            ['name' => 'Türkiye', 'code' => 'TR', 'phone' => 90],
            ['name' => 'Türkmenistan', 'code' => 'TM', 'phone' => 993],
            ['name' => 'Tuvalu', 'code' => 'TV', 'phone' => 688],
            ['name' => 'Uganda', 'code' => 'UG', 'phone' => 256],
            ['name' => 'Ukrayna', 'code' => 'UA', 'phone' => 380],
            ['name' => 'Birleşik Arap Emirlikleri', 'code' => 'AE', 'phone' => 971],
            ['name' => 'Birleşik Krallık', 'code' => 'GB', 'phone' => 44],
            ['name' => 'Amerika Birleşik Devletleri', 'code' => 'US', 'phone' => 1],
            ['name' => 'Uruguay', 'code' => 'UY', 'phone' => 598],
            ['name' => 'Özbekistan', 'code' => 'UZ', 'phone' => 998],
            ['name' => 'Vanuatu', 'code' => 'VU', 'phone' => 678],
            ['name' => 'Vatikan', 'code' => 'VA', 'phone' => 379],
            ['name' => 'Venezuela', 'code' => 'VE', 'phone' => 58],
            ['name' => 'Vietnam', 'code' => 'VN', 'phone' => 84],
            ['name' => 'Yemen', 'code' => 'YE', 'phone' => 967],
            ['name' => 'Zambiya', 'code' => 'ZM', 'phone' => 260],
            ['name' => 'Zimbabve', 'code' => 'ZW', 'phone' => 263]
        ];

        $states = [
            ['name' => 'Adana', 'code' => 1, 'phone' => 322],
            ['name' => 'Adıyaman', 'code' => 2, 'phone' => 416],
            ['name' => 'Afyonkarahisar', 'code' => 3, 'phone' => 272],
            ['name' => 'Ağrı', 'code' => 4, 'phone' => 472],
            ['name' => 'Amasya', 'code' => 5, 'phone' => 358],
            ['name' => 'Ankara', 'code' => 6, 'phone' => 312],
            ['name' => 'Antalya', 'code' => 7, 'phone' => 242],
            ['name' => 'Artvin', 'code' => 8, 'phone' => 466],
            ['name' => 'Aydın', 'code' => 9, 'phone' => 256],
            ['name' => 'Balıkesir', 'code' => 10, 'phone' => 266],
            ['name' => 'Bilecik', 'code' => 11, 'phone' => 228],
            ['name' => 'Bingöl', 'code' => 12, 'phone' => 426],
            ['name' => 'Bitlis', 'code' => 13, 'phone' => 434],
            ['name' => 'Bolu', 'code' => 14, 'phone' => 374],
            ['name' => 'Burdur', 'code' => 15, 'phone' => 248],
            ['name' => 'Bursa', 'code' => 16, 'phone' => 224],
            ['name' => 'Çanakkale', 'code' => 17, 'phone' => 286],
            ['name' => 'Çankırı', 'code' => 18, 'phone' => 376],
            ['name' => 'Çorum', 'code' => 19, 'phone' => 364],
            ['name' => 'Denizli', 'code' => 20, 'phone' => 258],
            ['name' => 'Diyarbakır', 'code' => 21, 'phone' => 412],
            ['name' => 'Edirne', 'code' => 22, 'phone' => 284],
            ['name' => 'Elazığ', 'code' => 23, 'phone' => 424],
            ['name' => 'Erzincan', 'code' => 24, 'phone' => 446],
            ['name' => 'Erzurum', 'code' => 25, 'phone' => 442],
            ['name' => 'Eskişehir', 'code' => 26, 'phone' => 222],
            ['name' => 'Gaziantep', 'code' => 27, 'phone' => 342],
            ['name' => 'Giresun', 'code' => 28, 'phone' => 454],
            ['name' => 'Gümüşhane', 'code' => 29, 'phone' => 456],
            ['name' => 'Hakkari', 'code' => 30, 'phone' => 438],
            ['name' => 'Hatay', 'code' => 31, 'phone' => 326],
            ['name' => 'Isparta', 'code' => 32, 'phone' => 246],
            ['name' => 'Mersin', 'code' => 33, 'phone' => 324],
            ['name' => 'İstanbul (Avrupa)', 'code' => 34, 'phone' => 212],
            ['name' => 'İstanbul (Anadolu)', 'code' => 34, 'phone' => 216],
            ['name' => 'İzmir', 'code' => 35, 'phone' => 232],
            ['name' => 'Kars', 'code' => 36, 'phone' => 474],
            ['name' => 'Kastamonu', 'code' => 37, 'phone' => 366],
            ['name' => 'Kayseri', 'code' => 38, 'phone' => 352],
            ['name' => 'Kırklareli', 'code' => 39, 'phone' => 288],
            ['name' => 'Kırşehir', 'code' => 40, 'phone' => 386],
            ['name' => 'Kocaeli', 'code' => 41, 'phone' => 262],
            ['name' => 'Konya', 'code' => 42, 'phone' => 332],
            ['name' => 'Kütahya', 'code' => 43, 'phone' => 274],
            ['name' => 'Malatya', 'code' => 44, 'phone' => 422],
            ['name' => 'Manisa', 'code' => 45, 'phone' => 236],
            ['name' => 'Kahramanmaraş', 'code' => 46, 'phone' => 344],
            ['name' => 'Mardin', 'code' => 47, 'phone' => 482],
            ['name' => 'Muğla', 'code' => 48, 'phone' => 252],
            ['name' => 'Muş', 'code' => 49, 'phone' => 436],
            ['name' => 'Nevşehir', 'code' => 50, 'phone' => 384],
            ['name' => 'Niğde', 'code' => 51, 'phone' => 388],
            ['name' => 'Ordu', 'code' => 52, 'phone' => 452],
            ['name' => 'Rize', 'code' => 53, 'phone' => 464],
            ['name' => 'Sakarya', 'code' => 54, 'phone' => 264],
            ['name' => 'Samsun', 'code' => 55, 'phone' => 362],
            ['name' => 'Siirt', 'code' => 56, 'phone' => 484],
            ['name' => 'Sinop', 'code' => 57, 'phone' => 368],
            ['name' => 'Sivas', 'code' => 58, 'phone' => 346],
            ['name' => 'Tekirdağ', 'code' => 59, 'phone' => 282],
            ['name' => 'Tokat', 'code' => 60, 'phone' => 356],
            ['name' => 'Trabzon', 'code' => 61, 'phone' => 462],
            ['name' => 'Tunceli', 'code' => 62, 'phone' => 428],
            ['name' => 'Şanlıurfa', 'code' => 63, 'phone' => 414],
            ['name' => 'Uşak', 'code' => 64, 'phone' => 276],
            ['name' => 'Van', 'code' => 65, 'phone' => 432],
            ['name' => 'Yozgat', 'code' => 66, 'phone' => 354],
            ['name' => 'Zonguldak', 'code' => 67, 'phone' => 372],
            ['name' => 'Aksaray', 'code' => 68, 'phone' => 382],
            ['name' => 'Bayburt', 'code' => 69, 'phone' => 458],
            ['name' => 'Karaman', 'code' => 70, 'phone' => 338],
            ['name' => 'Kırıkkale', 'code' => 71, 'phone' => 318],
            ['name' => 'Batman', 'code' => 72, 'phone' => 488],
            ['name' => 'Şırnak', 'code' => 73, 'phone' => 486],
            ['name' => 'Bartın', 'code' => 74, 'phone' => 378],
            ['name' => 'Ardahan', 'code' => 75, 'phone' => 478],
            ['name' => 'Iğdır', 'code' => 76, 'phone' => 476],
            ['name' => 'Yalova', 'code' => 77, 'phone' => 226],
            ['name' => 'Karabük', 'code' => 78, 'phone' => 370],
            ['name' => 'Kilis', 'code' => 79, 'phone' => 348],
            ['name' => 'Osmaniye', 'code' => 80, 'phone' => 328],
            ['name' => 'Düzce', 'code' => 81, 'phone' => 380]
        ];

        foreach ($countries as $country) {
            Country::create([
                'status' => $country['code'] === 'TR' ? Status::ACTIVE : Status::PASSIVE,
                'name' => $country['name'],
                'code' => $country['code'],
                'phone' => $country['phone'],
            ]);
        }

        $country = Country::where('code', 'TR')->first();
        foreach ($states as $state) {
            State::create([
                'status' => Status::ACTIVE,
                'name' => $state['name'],
                'code' => $state['code'],
                'phone' => $state['phone'],
                'country_id' => $country->id
            ]);
        }

    }
}
